# Generated by Django 3.1.3 on 2024-05-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLinkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_url', models.TextField()),
                ('short_url', models.TextField()),
                ('hash_value', models.IntegerField()),
                ('create_date', models.DateTimeField()),
            ],
        ),
    ]
