# Generated by Django 3.1.3 on 2024-05-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlinkmodel',
            name='hash_value',
            field=models.TextField(),
        ),
    ]
