# Generated by Django 3.1.3 on 2024-05-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20240524_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlinkmodel',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='삭제일'),
        ),
    ]
