# Generated by Django 3.1.3 on 2024-05-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_shortlinkmodel_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlinkmodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
